
import { Album } from './types';

export const MOCK_ALBUMS: Album[] = [
  {
    id: '1',
    title: 'Neon Echoes',
    coverImage: 'https://picsum.photos/seed/neon/800/800',
    description: 'A journey through a futuristic cyberpunk landscape where AI and humanity merge.',
    story: 'In the year 2088, the boundaries between the digital and the biological dissolved. This album captures the frequency of that evolution. Every beat was synthesized from the ambient noise of Neo-Tokyo, processed through quantum neural networks to evoke the feeling of rain hitting chrome.',
    releaseDate: '2024-10-15',
    tracks: [
      { id: 't1', title: 'Circuit Breath', duration: '3:45', audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3', mp3Url: '#', wavUrl: '#', genre: 'Synthwave' },
      { id: 't2', title: 'Digital Rain', duration: '4:12', audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3', mp3Url: '#', wavUrl: '#', genre: 'Ambient' },
      { id: 't3', title: 'Silicon Soul', duration: '3:20', audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3', mp3Url: '#', wavUrl: '#', genre: 'Industrial' },
    ]
  },
  {
    id: '2',
    title: 'Astral Serenity',
    coverImage: 'https://picsum.photos/seed/astral/800/800',
    description: 'Celestial harmonies inspired by the quietude of deep space.',
    story: 'Beyond the heliosphere lies a silence so profound it becomes a melody. Astral Serenity was composed by feeding telescope imagery of the Andromeda galaxy into the Suno Curator AI, translating light patterns into harmonic scales that resonate with the frequency of the universe.',
    releaseDate: '2024-11-20',
    tracks: [
      { id: 't4', title: 'Void Lullaby', duration: '5:30', audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3', mp3Url: '#', wavUrl: '#', genre: 'Space Ambient' },
      { id: 't5', title: 'Nebula Waltz', duration: '3:58', audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3', mp3Url: '#', wavUrl: '#', genre: 'Classical Crossover' },
    ]
  },
  {
    id: '3',
    title: 'Organic Rewire',
    coverImage: 'https://picsum.photos/seed/organic/800/800',
    description: 'The collision of nature sounds and algorithmic precision.',
    story: 'What happens when we teach an AI to feel the wind? Organic Rewire explores the synthesis of biometric data from ancient redwoods and the precision of algorithmic mathematics. It is a testament to the coexistence of the primitive and the advanced.',
    releaseDate: '2024-12-05',
    tracks: [
      { id: 't6', title: 'Root Frequency', duration: '4:45', audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3', mp3Url: '#', wavUrl: '#', genre: 'Folktronica' },
      { id: 't7', title: 'Photosynthesis', duration: '3:15', audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3', mp3Url: '#', wavUrl: '#', genre: 'IDM' },
    ]
  },
  {
    id: '4',
    title: 'Ethereal Echoes',
    coverImage: 'https://picsum.photos/seed/ethereal/800/800',
    description: 'Hauntingly beautiful vocaloids and phantom melodies.',
    story: 'Recorded in the echoes of a digital graveyard, this album features phantom vocals generated by AI interpreting lost poetry from the 19th century. It is a bridge between eras, a ghostly resonance of what once was and what will be.',
    releaseDate: '2025-01-10',
    tracks: [
      { id: 't8', title: 'Phantom Verse', duration: '4:02', audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3', mp3Url: '#', wavUrl: '#', genre: 'Dream Pop' },
      { id: 't9', title: 'Gilded Shadow', duration: '3:50', audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3', mp3Url: '#', wavUrl: '#', genre: 'Alternative' },
    ]
  }
];
